export const ROUTES = {
  ALL_PRODUCT: "/home-page",
  NEW_PRODUCT: "/new-product",
  HOT_PRODUCT: "/hot-product",
  HEART_PRODUCT: "/heart-product",
  POTION_PRODUCT: "/potion-product",
  BEAUTY_PRODUCT: "/beauty-product",
  BODY_PRODUCT: "/body-product",
  SHOWER_PRODUCT: "/shower-product",
  CART: "/my-cart",
  HISTORY_ORDER: "/history-order",
  NOTIFICATION: "/notification",
  PAYMENT_PRODUCT: "/payment-product",
  FORYOU_PRODUCT: "/for-you-product",
  FAVORITE_PRODUCT: "/favorite-product",
  BEST_SELLER: "/best-seller",
  HOT_BRAND: "/hot-brand",
  HOT_COMBO: "/hot-combo",
  HEIGHT_PLUS: "/height-plus",
  ACOUNT_LOGIN: "/acount-login",
  ACOUNT_REGISTER: "/acount-register",
  DETAIL_PRODUCT: "/detail-product",
};
